'use client';
import { ArrowRight, ArrowUpRight, Check } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { useLanguage } from './context';
export const faqs=[
 ['Was genau ist ein Erinnerungsspiel?','What is a memory game?','Ein persönliches Spiel, das eure gemeinsamen Orte, Erlebnisse und Botschaften zu einer interaktiven Geschichte verbindet. Ihr liefert die Erinnerungen, daraus wird die Grundlage für euer Spiel.','A personal game that brings your shared places, experiences, and messages together in an interactive story. Your memories form the foundation of your game.'],
 ['Muss ich programmieren können?','Do I need to know how to code?','Nein. Im Studio sammelst du Namen, Erinnerungen, Bilder und deine persönliche Nachricht. Du wirst Schritt für Schritt durch die Vorbereitung geführt.','No. Collect names, memories, images, and your personal message in the studio. You are guided through the preparation step by step.'],
 ['Wer sieht meine Erinnerungen und Bilder?','Who can see my memories and images?','Dein Entwurf ist deinem angemeldeten Konto zugeordnet. Deine Inhalte werden in dieser Version nicht veröffentlicht oder mit anderen Kunden geteilt. Verwende in der privaten Testphase bitte nur Testinhalte.','Your draft belongs to your signed-in account. Your content is not published or shared with other customers in this version. Please only use test content during the private test phase.'],
 ['Was kostet das fertige Spiel?','How much does the finished game cost?','Ein Verkaufspreis steht noch nicht fest. Du kannst den Entwurfsbereich ohne Kauf testen. Eine Bestellung oder Zahlung ist hier noch nicht möglich.','The sale price has not been set. You can try the draft editor without a purchase. Orders and payments are not available yet.'],
 ['Was kann ich hier bereits machen?','What can I do here already?','Du kannst eine Geschichte anlegen, deine Texte und Bilder speichern und den Entwurf später weiterbearbeiten. Die eigentliche Spielproduktion und die Auslieferung werden anschließend eingerichtet.','You can create a story, save your text and images, and continue editing later. Game production and delivery will be connected subsequently.'],
 ];
 export function FAQList(){const{lang}=useLanguage();return <Accordion type="single" collapsible className="faq-list">{faqs.map((faq,i)=><AccordionItem value={`faq-${i}`} key={i}><AccordionTrigger>{faq[lang==='de'?0:1]}</AccordionTrigger><AccordionContent>{faq[lang==='de'?2:3]}</AccordionContent></AccordionItem>)}</Accordion>;}
export function MarketingRest(){const{t}=useLanguage();return <><section id="how" className="section wrap"><div className="section-heading"><div><p className="eyebrow">{t('VON „WEISST DU NOCH?“ ZU „WOW.“','FROM “REMEMBER WHEN?” TO “WOW.”')}</p><h2>{t('Eure Momente rein.','Your moments in.')}<br/>{t('Ein Abenteuer raus.','An adventure out.')}</h2></div><p>{t('Du bringst die Erinnerungen mit. Im Studio setzt du sie Schritt für Schritt zu eurer Geschichte zusammen.','Bring your memories. Build your story in the studio, one small step at a time.')}</p></div><div className="how-grid">{[
 [t('Erzählt von euch.','Tell your story.'),t('Wer seid ihr? Was bringt euch zum Lachen? Welche kleinen Augenblicke sind geblieben? Drei Erinnerungen sind ein guter Anfang.','Who are you? What makes you laugh? Which little moments stayed with you? Three memories are a great beginning.')],
 [t('Macht es persönlich.','Make it personal.'),t('Eure Namen, eure Worte, deine letzte Nachricht. Im Studio gestaltest und speicherst du die Inhalte für euer persönliches Spiel.','Your names, your words, your final message. Shape and save the content for your personal game in the studio.')],
 [t('Bewahrt eure Geschichte.','Keep your story.'),t('Lies alles noch einmal in Ruhe durch. Dein Entwurf bleibt gespeichert, bis ihr bereit für das nächste Kapitel seid.','Read it through in your own time. Your draft stays saved until you’re ready for the next chapter.')],
 ].map(([heading,text],i)=><article key={i}><span className="how-number">{i+1}</span><h3>{heading}</h3><p>{text}</p></article>)}</div></section><section id="packages" className="offer-section"><div className="offer-layout wrap"><div><p className="eyebrow">{t('FÜR EUCH. NICHT FÜR IRGENDWEN.','FOR YOU. NOT JUST ANYONE.')}</p><h2>{t('Der Anlass ist schön.','The occasion is lovely.')}<br/>{t('Ihr seid der Grund.','You are the reason.')}</h2><p>{t('Zum Jahrestag, zum Geburtstag oder an einem ganz normalen Dienstag. Manche Menschen verdienen ein Geschenk, das ihre Geschichte erzählt.','For an anniversary, a birthday, or an ordinary Tuesday. Some people deserve a gift that tells their story.')}</p></div><div className="offer-card"><span className="tag">{t('HIER BEGINNT EURE GESCHICHTE','YOUR STORY BEGINS HERE')}</span><h3>{t('Euer erstes Kapitel.','Your first chapter.')}</h3><p>{t('Ein persönlicher Anfang. Ganz ohne Kauf.','A personal beginning. No purchase required.')}</p><ul className="check-list">{[t('Eure Namen und drei Erinnerungen','Your names and three memories'),t('Eine Nachricht für den letzten Moment','A message for the final moment'),t('Bilder als private Referenzen','Images as private references'),t('Privater Entwurf mit automatischem Speichern','Private draft with automatic saving')].map(item=><li key={item}><Check/>{item}</li>)}</ul><a href="/create" className="button">{t('Kostenlosen Entwurf gestalten','Create a free draft')}<ArrowUpRight size={18}/></a><small>{t('Preis und Verkaufsstart des fertigen Produkts folgen.','Finished product pricing and launch date to follow.')}</small></div></div></section><section className="section wrap faq-layout"><div><h2>{t('Gut zu wissen.','Good to know.')}</h2><a className="text-link" href="/help">{t('Alle Fragen & Hilfe','All questions & help')}<ArrowRight size={18}/></a></div><FAQList/></section><section className="closing-cta wrap"><h2>{t('Welche Erinnerung wird euer erstes Level?','Which memory will be your first level?')}</h2><p>{t('Fang mit dem Moment an, bei dem du gerade lächeln musst.','Start with the moment that’s making you smile right now.')}</p><a className="button" href="/create">{t('Eure Geschichte starten','Start your story')}<ArrowUpRight size={18}/></a></section></>;}
