'use client';
import { ArrowUpRight, Play, Menu } from 'lucide-react';
import { useLanguage } from './context';
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';
export function Brand() { return <a href="/" className="brand" aria-label="Your story — Home"><span className="brand-mark"><Play size={20} fill="currentColor" /></span><span>your story.<small>made playable</small></span></a>; }
export function Header() {
 const {lang,t,toggle} = useLanguage();
 return <header className="site-header wrap"><Brand /><nav className="desktop-nav" aria-label={t('Hauptnavigation','Main navigation')}><a href="/#experience">{t('Das Erlebnis','The experience')}</a><a href="/#how">{t('So funktioniert’s','How it works')}</a><a href="/#packages">{t('Dein Spiel','Your game')}</a><a href="/demo">{t('Demo spielen','Play demo')}</a></nav><div className="header-actions"><button className="language" onClick={toggle} aria-label={t('Switch to English','Auf Deutsch wechseln')}>{lang.toUpperCase()} <span>⌄</span></button><a className="studio-link" href="/studio">{t('Mein Studio','My studio')}</a><a href="/create" className="button small desktop-start">{t('Loslegen','Get started')}<ArrowUpRight size={16}/></a><Sheet><SheetTrigger className="mobile-menu" aria-label={t('Menü öffnen','Open menu')}><Menu/></SheetTrigger><SheetContent><SheetTitle>{t('Entdecke deine Geschichte','Explore your story')}</SheetTitle><SheetDescription>{t('Ein persönliches Spiel beginnt mit euch.','A personal game starts with you.')}</SheetDescription><nav className="mobile-links"><a href="/#experience">{t('Das Erlebnis','The experience')}</a><a href="/#how">{t('So funktioniert’s','How it works')}</a><a href="/demo">{t('Demo spielen','Play demo')}</a><a href="/studio">{t('Mein Studio','My studio')}</a><a className="button" href="/create">{t('Geschichte starten','Start your story')}</a></nav></SheetContent></Sheet></div></header>;
}
export function Footer() { const {t}=useLanguage(); return <footer className="site-footer wrap"><div><Brand/><p>{t('Für die Geschichten, die nur ihr erzählen könnt.','For the stories only you can tell.')}</p></div><nav><a href="/help">{t('Fragen & Hilfe','Questions & help')}</a><a href="/privacy">{t('Datenschutz','Privacy')}</a><a href="/legal">{t('Impressum','Legal')}</a></nav><small>{t('Produktvorschau · Verkauf noch nicht aktiviert','Product preview · Sales are not yet enabled')}</small></footer>; }
